services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Монтируем код
    working_dir: /app
    command: npm run start:dev
    depends_on:
      - postgres